#!/usr/bin/env python
"""Build the book — and the standalone chapter offprints — from the executed notebooks.

    python book/build.py              # macros + floats + book.pdf + every chapter PDF
    python book/build.py --chapter geo_lift
    python book/build.py --no-chapters

The pipeline, and the one invariant it exists to enforce:

    notebooks (executed)  --cmp.report-->  build/results.json
                                              |
              write_macros()  ---------------.|.--------------- generate_floats()
                     |                                                |
              build/macros.tex                              build/floats/*.tex
              (one \\newcommand per number)                 (figure floats, captions and all)
                     |                                                |
                     '---------> xelatex + biber + xelatex <----------'
                                       |                |
                                 build/book.pdf   build/ch09_geo_lift.pdf

**No number is retyped into the chapter.** The prose cites macros; the captions were authored
next to the computation that produced them. So a *stale* number is impossible, and a *missing*
one is an "Undefined control sequence" — which this script treats as a hard failure and refuses
to ship a PDF for, even though xelatex in non-stop mode would happily emit one with a hole in it.
That refusal is the point: a hole is louder than a stale number.
"""
from __future__ import annotations

import argparse
import contextlib
import fcntl
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

BOOK = Path(__file__).resolve().parent
REPO = BOOK.parent
BUILD = BOOK / "build"
sys.path.insert(0, str(REPO / "src"))

XELATEX = shutil.which("xelatex") or "/Library/TeX/texbin/xelatex"
BIBER = shutil.which("biber") or "/Library/TeX/texbin/biber"

# The chapters, in book order: (source stem, the chapter number MINUS ONE, offprint name).
# The offprint carries the book's own chapter/equation/float numbers — an offprint, not a
# second edition — so a reader can be handed Chapter 9 alone and still find Table 9.2 in it.
#
# A stem whose .tex does not exist yet is SKIPPED with a warning rather than failing the build:
# the chapters land one at a time, and a half-written book must still compile so the chapters
# that ARE done can be read.
CHAPTERS = [
    ("foundations",        0, "ch01_foundations"),
    ("point_vs_posterior", 1, "ch02_point_vs_posterior"),
    ("uplift",             2, "ch03_uplift"),
    ("segment_effects",    3, "ch04_segment_effects"),
    ("price_elasticity",   4, "ch05_price_elasticity"),
    ("mediation",          5, "ch06_mediation"),
    ("what_to_control",    6, "ch07_what_to_control"),
    ("mmm",                7, "ch08_mmm"),
    ("geo_lift",           8, "ch09_geo_lift"),
    ("did",                9, "ch10_did"),
    ("rdd",               10, "ch11_rdd"),
    ("its",               11, "ch12_its"),
    ("iv",                12, "ch13_iv"),
]


# ---------------------------------------------------------------------------- floats
def escape_bare_percent(s: str) -> str:
    r"""Escape a `%` that is not already escaped.

    Captions are authored in the notebook and are deliberately allowed to carry LaTeX
    (`$\times$`, `90\,\%`). But a *bare* `%` — as in "at the 15% shift" — starts a LaTeX comment,
    which silently swallows the rest of the caption INCLUDING its closing brace. The failure then
    surfaces hundreds of lines later as "File ended while scanning use of \caption@xdblarg", which
    points at the wrong file entirely. So: escape bare `%`, leave `\%` alone.
    """
    return re.sub(r"(?<!\\)%", r"\\%", s)


def generate_floats() -> int:
    """Turn every figure emitted by `cmp.report.figure` into a complete LaTeX float.

    The caption is generated too, and deliberately so: captions in this book carry numbers
    ("covers the true path 86 % of the time"), and a caption is exactly the place where a
    retyped number would go unnoticed for a year. So captions are authored *in the notebook*,
    beside the computation, and travel with the figure.
    """
    from cmp import report
    results = report.load()                    # merges build/results/nb*.json (one shard per notebook)
    out = BUILD / "floats"
    out.mkdir(parents=True, exist_ok=True)
    n = 0
    for key, rec in sorted(results.items()):
        if rec.get("kind") != "figure":
            continue
        stem = key.replace(".", "_")
        pdf = Path(rec["path"]).name
        (out / f"{stem}.tex").write_text(
            "% Generated by book/build.py from an executed notebook — do not edit.\n"
            # [tb], not [htbp] — see the note in cmp.report.table: "here" strands a float
            # mid-page with white space above and below it. Top or bottom only, so the text
            # closes over it. The float fractions in book/preamble.tex keep a slot available.
            "\\begin{figure}[tb]\n"
            "  \\centering\n"
            f"  \\includegraphics[width={rec.get('width', r'\linewidth')}]{{{pdf}}}\n"
            f"  \\caption{{{escape_bare_percent(rec['caption'])}}}\n"
            f"  \\label{{{rec['label']}}}\n"
            "\\end{figure}\n"
        )
        n += 1
    return n


def fit_tables() -> int:
    """Make every generated table fit the text block.

    A results table with seven columns does not fit an A4 text block at body size, and LaTeX's
    response is to run it into the margin rather than complain loudly — the worst offender here
    overran by 101pt (over a third of an inch). `adjustbox`'s `max width` shrinks a table only if
    it would overflow and leaves the rest untouched, which is why it is right where
    \\resizebox{\\linewidth} would be wrong: that would also *enlarge* a two-column table to full
    width.

    Applied here, at build time, rather than in `cmp.report.table`, so that fixing the typography
    does not mean re-executing fourteen notebooks (the MMM alone is a 40-minute sampler run).
    """
    n = 0
    for path in sorted((BUILD / "tables").glob("*.tex")):
        body = path.read_text()
        if "adjustbox" in body:
            continue
        if r"\begin{tabular}" not in body:
            continue
        body = body.replace(r"\begin{tabular}",
                            "\\begin{adjustbox}{max width=\\linewidth}\n\\begin{tabular}", 1)
        body = body.replace(r"\end{tabular}",
                            "\\end{tabular}\n\\end{adjustbox}", 1)
        path.write_text(body)
        n += 1
    return n


# ---------------------------------------------------------------------------- latex
def _run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)


def _check_log(log: Path, what: str) -> None:
    """A missing macro must never ship silently."""
    if not log.exists():
        sys.exit(f"FAIL {what}: no log at {log}")
    text = log.read_text(errors="replace")
    undefined = sorted(set(re.findall(r"Undefined control sequence.*?\n.*?(\\[A-Za-z@]+)", text,
                                      re.S)))
    if undefined:
        sys.exit(f"FAIL {what}: undefined macro(s) {' '.join(undefined)}\n"
                 f"       Every number in the prose must come from a notebook. Emit it with\n"
                 f"       cmp.report.value(...), re-run the notebook, and rebuild.")
    fatal = [ln for ln in text.splitlines() if ln.startswith("! ")]
    if fatal:
        sys.exit(f"FAIL {what}: {fatal[0]}\n       see {log}")


_LOCK_DEPTH = 0


@contextlib.contextmanager
def _build_lock():
    """Serialise LaTeX runs across PROCESSES.

    Every xelatex run writes build/<jobname>.aux and, because of `\\include`, one aux file per
    chapter under build/chapters/. Two `build.py` processes running at once therefore write the
    same aux files, and a run that reads an aux another run is halfway through writing dies with
    a baffling error ("Missing \\begin{document}") that has nothing to do with the chapter being
    compiled. The chapters are authored concurrently, so this is not hypothetical — it was
    observed. A single lock is enough: LaTeX is fast, and correctness beats parallelism here.
    """
    global _LOCK_DEPTH
    if _LOCK_DEPTH:                       # reentrant: main() already holds it
        yield
        return
    lock = BUILD / ".build.lock"
    lock.parent.mkdir(parents=True, exist_ok=True)
    with open(lock, "w") as fh:
        fcntl.flock(fh, fcntl.LOCK_EX)    # blocks until the other build.py finishes
        _LOCK_DEPTH += 1
        try:
            yield
        finally:
            _LOCK_DEPTH -= 1
            fcntl.flock(fh, fcntl.LOCK_UN)


def _clear_aux(jobname: str) -> None:
    """Remove the aux files a run reads back on its second pass."""
    for p in [BUILD / f"{jobname}.aux", BUILD / f"{jobname}.toc", BUILD / f"{jobname}.bcf",
              *(BUILD / "chapters").glob("*.aux")]:
        p.unlink(missing_ok=True)


def compile_tex(jobname: str, source: str, tex_cmd: str | None = None, bib: bool = True) -> Path:
    with _build_lock():
        try:
            return _compile_tex(jobname, source, tex_cmd, bib)
        except SystemExit:
            # A corrupt aux is STICKY: pass 1 reads it, dies under -halt-on-error, and never gets
            # far enough to rewrite it — so every subsequent build fails too, with an error
            # ("Missing \begin{document}") that has nothing to do with the source. The aux is pure
            # derived state, so throwing it away costs one pass and can lose nothing. Retry once.
            print(f"  {jobname}: build failed — clearing aux and retrying once")
            _clear_aux(jobname)
            return _compile_tex(jobname, source, tex_cmd, bib)


def _compile_tex(jobname: str, source: str, tex_cmd: str | None = None, bib: bool = True) -> Path:
    (BUILD / "chapters").mkdir(parents=True, exist_ok=True)   # \include writes aux files here
    args = ["-interaction=nonstopmode", "-halt-on-error", "-file-line-error",
            "-output-directory=build", f"-jobname={jobname}"]
    target = tex_cmd or source
    for i in range(3):
        r = _run([XELATEX, *args, target], BOOK)
        if i == 0 and bib:
            b = _run([BIBER, "--input-directory=build", "--output-directory=build", jobname], BOOK)
            if b.returncode != 0 and "please (re)run" not in (b.stdout + b.stderr):
                print(f"  biber warning ({jobname}): {b.stdout.strip().splitlines()[-1:]}")
        if r.returncode != 0 and i == 2:
            _check_log(BUILD / f"{jobname}.log", jobname)          # gives the real message
            sys.exit(f"FAIL {jobname}: xelatex exited {r.returncode}; see build/{jobname}.log")
    _check_log(BUILD / f"{jobname}.log", jobname)
    pdf = BUILD / f"{jobname}.pdf"
    if not pdf.exists():
        sys.exit(f"FAIL {jobname}: no PDF produced")
    return pdf


def pages(jobname: str) -> str:
    """Page count, read off the xelatex log (the PDF's object streams are compressed, so
    grepping the PDF for /Type /Page finds nothing)."""
    log = (BUILD / f"{jobname}.log").read_text(errors="replace")
    n = re.search(r"Output written on .*?\((\d+) pages?", log)
    return n.group(1) if n else "?"


# ---------------------------------------------------------------------------- main
def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--chapter", help="build only this chapter's offprint (and the book)")
    ap.add_argument("--no-chapters", action="store_true", help="book only, no offprints")
    ap.add_argument("--no-book", action="store_true", help="offprints only")
    args = ap.parse_args()

    from cmp import report                                   # noqa: E402  (needs sys.path above)

    if not report.load():
        sys.exit("FAIL: no results in book/build/results/ — execute the notebooks first "
                 "(CMP_FAST=0), so they can emit their results.")

    # The iron rule has a mode dimension: a number that is *current* but came from a FAST run
    # (short chains, few seeds) is as wrong for the book as a stale one. Every shard carries a
    # `_meta` stamp written at emit time; refuse to typeset from a shard that is FAST or
    # predates the stamp. (This fired for real once: a FAST nb04.json with ESS 444 sat where
    # the FULL run's ESS 3737 belonged, and the build sailed on.)
    stale = report.stale_shards()
    if stale:
        sys.exit(
            "FAIL: these result shards were not produced by a FULL run (CMP_FAST=0): "
            + ", ".join(stale)
            + " — re-execute those notebooks with CMP_FAST=0 before building the book."
        )

    # One lock for the whole run: macros.tex and the aux files are shared state, and the chapters
    # are authored by concurrent agents each invoking this script.
    with _build_lock():
        macros = report.write_macros()
        n_macros = sum(1 for ln in macros.read_text().splitlines()
                       if ln.startswith(r"\newcommand"))
        n_floats = generate_floats()
        n_tables = len(list((BUILD / "tables").glob("*.tex")))
        n_fitted = fit_tables()
        print(f"macros.tex: {n_macros} numbers · {n_floats} figure floats · {n_tables} tables "
              f"— all from executed notebooks")
        if n_fitted:
            print(f"fitted {n_fitted} tables to the text block (adjustbox max width)")

        if not args.no_book:
            pdf = compile_tex("book", "book.tex")
            print(f"book:     {pdf.relative_to(REPO)}  ({pages('book')} pages)")

        if not args.no_chapters:
            for stem, before, jobname in CHAPTERS:
                if args.chapter and args.chapter != stem:
                    continue
                if not (BOOK / "chapters" / f"{stem}.tex").exists():
                    print(f"  skip {stem}: not written yet")
                    continue
                cmd = (rf"\def\chapterfile{{chapters/{stem}}}"
                       rf"\def\chapternumber{{{before}}}\input{{chapter.tex}}")
                pdf = compile_tex(jobname, "chapter.tex", tex_cmd=cmd)
                print(f"offprint: {pdf.relative_to(REPO)}  ({pages(jobname)} pages)")


if __name__ == "__main__":
    os.chdir(BOOK)
    main()
