#!/usr/bin/env python
"""Build the book — and the standalone chapter offprints — from the executed notebooks.

    python book/build.py              # macros + floats + book.pdf + every chapter PDF
    python book/build.py --chapter geo_lift
    python book/build.py --no-chapters

The pipeline, and the one invariant it exists to enforce:

    notebooks (executed)  --cmp.report-->  build/results.json
                                              |
              write_macros()  ---------------.|.--------------- generate_floats()
                     |                                                |
              build/macros.tex                              build/floats/*.tex
              (one \\newcommand per number)                 (figure floats, captions and all)
                     |                                                |
                     '---------> xelatex + biber + xelatex <----------'
                                       |                |
                                 build/book.pdf   build/ch09_geo_lift.pdf

**No number is retyped into the chapter.** The prose cites macros; the captions were authored
next to the computation that produced them. So a *stale* number is impossible, and a *missing*
one is an "Undefined control sequence" — which this script treats as a hard failure and refuses
to ship a PDF for, even though xelatex in non-stop mode would happily emit one with a hole in it.
That refusal is the point: a hole is louder than a stale number.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

BOOK = Path(__file__).resolve().parent
REPO = BOOK.parent
BUILD = BOOK / "build"
sys.path.insert(0, str(REPO / "src"))

XELATEX = shutil.which("xelatex") or "/Library/TeX/texbin/xelatex"
BIBER = shutil.which("biber") or "/Library/TeX/texbin/biber"

# The chapters, in book order: (source stem, the chapter number MINUS ONE, offprint name).
# The offprint carries the book's own chapter/equation/float numbers — an offprint, not a
# second edition — so a reader can be handed Chapter 9 alone and still find Table 9.2 in it.
CHAPTERS = [
    ("geo_lift", 8, "ch09_geo_lift"),
]


# ---------------------------------------------------------------------------- floats
def generate_floats() -> int:
    """Turn every figure emitted by `cmp.report.figure` into a complete LaTeX float.

    The caption is generated too, and deliberately so: captions in this book carry numbers
    ("covers the true path 86 % of the time"), and a caption is exactly the place where a
    retyped number would go unnoticed for a year. So captions are authored *in the notebook*,
    beside the computation, and travel with the figure.
    """
    from cmp import report
    results = report.load()                    # merges build/results/nb*.json (one shard per notebook)
    out = BUILD / "floats"
    out.mkdir(parents=True, exist_ok=True)
    n = 0
    for key, rec in sorted(results.items()):
        if rec.get("kind") != "figure":
            continue
        stem = key.replace(".", "_")
        pdf = Path(rec["path"]).name
        (out / f"{stem}.tex").write_text(
            "% Generated by book/build.py from an executed notebook — do not edit.\n"
            "\\begin{figure}[htbp]\n"
            "  \\centering\n"
            f"  \\includegraphics[width={rec.get('width', r'\linewidth')}]{{{pdf}}}\n"
            f"  \\caption{{{rec['caption']}}}\n"
            f"  \\label{{{rec['label']}}}\n"
            "\\end{figure}\n"
        )
        n += 1
    return n


# ---------------------------------------------------------------------------- latex
def _run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)


def _check_log(log: Path, what: str) -> None:
    """A missing macro must never ship silently."""
    if not log.exists():
        sys.exit(f"FAIL {what}: no log at {log}")
    text = log.read_text(errors="replace")
    undefined = sorted(set(re.findall(r"Undefined control sequence.*?\n.*?(\\[A-Za-z@]+)", text,
                                      re.S)))
    if undefined:
        sys.exit(f"FAIL {what}: undefined macro(s) {' '.join(undefined)}\n"
                 f"       Every number in the prose must come from a notebook. Emit it with\n"
                 f"       cmp.report.value(...), re-run the notebook, and rebuild.")
    fatal = [ln for ln in text.splitlines() if ln.startswith("! ")]
    if fatal:
        sys.exit(f"FAIL {what}: {fatal[0]}\n       see {log}")


def compile_tex(jobname: str, source: str, tex_cmd: str | None = None, bib: bool = True) -> Path:
    (BUILD / "chapters").mkdir(parents=True, exist_ok=True)   # \include writes aux files here
    args = ["-interaction=nonstopmode", "-halt-on-error", "-file-line-error",
            "-output-directory=build", f"-jobname={jobname}"]
    target = tex_cmd or source
    for i in range(3):
        r = _run([XELATEX, *args, target], BOOK)
        if i == 0 and bib:
            b = _run([BIBER, "--input-directory=build", "--output-directory=build", jobname], BOOK)
            if b.returncode != 0 and "please (re)run" not in (b.stdout + b.stderr):
                print(f"  biber warning ({jobname}): {b.stdout.strip().splitlines()[-1:]}")
        if r.returncode != 0 and i == 2:
            _check_log(BUILD / f"{jobname}.log", jobname)          # gives the real message
            sys.exit(f"FAIL {jobname}: xelatex exited {r.returncode}; see build/{jobname}.log")
    _check_log(BUILD / f"{jobname}.log", jobname)
    pdf = BUILD / f"{jobname}.pdf"
    if not pdf.exists():
        sys.exit(f"FAIL {jobname}: no PDF produced")
    return pdf


def pages(jobname: str) -> str:
    """Page count, read off the xelatex log (the PDF's object streams are compressed, so
    grepping the PDF for /Type /Page finds nothing)."""
    log = (BUILD / f"{jobname}.log").read_text(errors="replace")
    n = re.search(r"Output written on .*?\((\d+) pages?", log)
    return n.group(1) if n else "?"


# ---------------------------------------------------------------------------- main
def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--chapter", help="build only this chapter's offprint (and the book)")
    ap.add_argument("--no-chapters", action="store_true", help="book only, no offprints")
    ap.add_argument("--no-book", action="store_true", help="offprints only")
    args = ap.parse_args()

    from cmp import report                                   # noqa: E402  (needs sys.path above)

    if not report.load():
        sys.exit("FAIL: no results in book/build/results/ — execute the notebooks first "
                 "(CMP_FAST=0), so they can emit their results.")

    macros = report.write_macros()
    n_macros = sum(1 for ln in macros.read_text().splitlines() if ln.startswith(r"\newcommand"))
    n_floats = generate_floats()
    n_tables = len(list((BUILD / "tables").glob("*.tex")))
    print(f"macros.tex: {n_macros} numbers · {n_floats} figure floats · {n_tables} tables "
          f"— all from executed notebooks")

    if not args.no_book:
        pdf = compile_tex("book", "book.tex")
        print(f"book:     {pdf.relative_to(REPO)}  ({pages('book')} pages)")

    if not args.no_chapters:
        for stem, before, jobname in CHAPTERS:
            if args.chapter and args.chapter != stem:
                continue
            cmd = (rf"\def\chapterfile{{chapters/{stem}}}"
                   rf"\def\chapternumber{{{before}}}\input{{chapter.tex}}")
            pdf = compile_tex(jobname, "chapter.tex", tex_cmd=cmd)
            print(f"offprint: {pdf.relative_to(REPO)}  ({pages(jobname)} pages)")


if __name__ == "__main__":
    os.chdir(BOOK)
    main()
